apiVersion: v1
kind: Service
metadata:
  name: application-service
spec:
  type: ClusterIP
  selector:
    app: application
  ports:
    - port: 8080
      targetPort: 8888 # point to Gateway-Proxy instead of App
