apiVersion: v1
kind: ConfigMap
metadata:
  name: hazelcast-configmap
data:
  hazelcast.yaml: |-
    hazelcast:
      cluster-name: hzcluster
      network:
        join:
          multicast:
            enabled: false
          kubernetes:
            enabled: true
            service-name: hazelcast-service
      map:
        default:
          time-to-live-seconds: 20
        main-cache:
          time-to-live-seconds: 5