apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      serviceAccountName: hazelcast-service-account
      containers:
        - name: application
          image: bitxon/app-hz-embedded
          ports:
            - containerPort: 8080
            - containerPort: 5701