apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: hazelcast-embedded
manifests:
  rawYaml:
    - k8s/hazelcast-rbac.yaml
    - k8s/hazelcast-service.yaml
    - k8s/app-deployment.yaml
    - k8s/app-service.yaml
