apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
        - name: application
          image: bitxon/app-hz-sidecar
          ports:
            - containerPort: 8080
        - name: hazelcast
          image: hazelcast/hazelcast
          ports:
            - containerPort: 5701