name: CI/CD Build

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build hazelcast-embedded
        run: mvn clean verify -B -Daether.dependencyCollector.impl=bf
        working-directory: hazelcast-embedded

      - name: Build hazelcast-sidecar
        run: mvn clean verify -B -Daether.dependencyCollector.impl=bf
        working-directory: hazelcast-sidecar

      - name: Build hazelcast-client-server
        run: mvn clean verify -B -Daether.dependencyCollector.impl=bf
        working-directory: hazelcast-client-server

      - name: Build hazelcast-reverse-proxy-sidecar
        run: mvn clean verify -B -Daether.dependencyCollector.impl=bf
        working-directory: hazelcast-reverse-proxy-sidecar
